### ISSUE TITLE
Instructions on how to build on MSVS 2013

### ISSUE THREAD

**Issue by manasabi** [djpnewton/busdog#19]
Hi,

Thanks for upgrading Busdog to MSVS2013. 

I am trying to build the GUI and filter driver together but I am running into some issues. Like busdog.exe which is generated after compiling the code under "gui/", gives error while installing the driver: "ExtractDriverFiles failed"

I guess this is because I am not compiling the GUI with driver as a resource. Also, running make_package.bat and make_all_package.bat throws error: "SignTool Error: File not found: filter\objfre_wxp_x86\i386\busdog.sys"

I tried following instructions mentioned in the wiki here: https://code.google.com/p/busdog/wiki/BuildingBusdog . But I think these instructions are outdated after the migration to MSVS 2013.

So, I wanted to request you if you could help me with instructions on how to build the latest version of Busdog.

Thanks
Manas

**Comment by djpnewton** [comment]
Yes the build scripts are out of date after the MSVS 2013 migration. I take it you are able to build the gui and the filter driver separately?

The process should eventually be:
  - build busdog.sys
  - sign busdog.sys
  - add busdog.sys/inf (+ other driver dependencies like WDF dlls etc) to a .NET resource
  - build busdog.exe with the driver resource

**Comment by djpnewton** [comment]
check out ef417530489178dc160acb4385ad3e9e40a32ed3 just be aware that you may need to use system restore if you install an unsigned filter driver

**Comment by manasabi** [comment]
It works now. Thanks a lot :)
