### ISSUE TITLE
Error during uninstall and reinstall (with admin right)

### ISSUE THREAD

**Issue by ghost** [djpnewton/busdog#22]
Hello,

First I love your project and without it, I will not be able to do my professional project that I am working on actually, it's much easier to use your tool than other software.

Thank you very much 👌

But I got a problem, I asked a friend to install your software through https://code.google.com/archive/p/busdog/downloads
But all his USB devices was turning off and forever, even after a reboot, so now he have factory reset his PC :/

So I decided to try to uninstall/reinstall to see if I have the same thing and yes.

I got this error when I try to doing that

![2018-03-01](https://user-images.githubusercontent.com/36959760/36849314-fe017b74-1d63-11e8-8ee7-14af464aeaa9.png)

So I decided to remove myself the BusDog ("C:\Windows\System32\drivers\busdog.sys") manually with unlocker, but after restarting the PC, all my USB device was dead.

And the only option to restore them is it put the driver back.

I am stuck, please help me 😭

**Comment by djpnewton** [comment]
the driver is installed as a USB class filter and so effects all the usb devices, so removing the binary (busdog.sys) will cause those devices not to work anymore.

before removing the busdog.sys binary, the driver needs to be removed as USB class filter (essentially changing a registry setting)

**Comment by ghost** [comment]
Oh thank you, I will try that 👍
